/**
 * @openbindings/sdk is the facade over the layered OpenBindings packages:
 *
 *   - @openbindings/core — the spec-defined document model (parse, validate,
 *     resolve, verify)
 *   - @openbindings/invoke — the binding-invoker / operation-invoker pattern
 *   - @openbindings/synthesize — the interface-synthesizer / source-inspector
 *     pattern
 *   - @openbindings/compare — schema comparison under the published
 *     schema-comparison profile (OB-2020-12)
 *
 * Every name exported here re-exports from the package that owns it; existing
 * consumers keep importing from "@openbindings/sdk" unchanged. New consumers
 * that want a smaller dependency surface import the layered packages
 * directly.
 */

// ---------------------------------------------------------------------------
// @openbindings/core
// ---------------------------------------------------------------------------

export type {
  JSONSchema,
  OperationExample,
  Operation,
  Source,
  Transform,
  TransformOrRef,
  TransformRef,
  BindingEntry,
  OBInterface,
  ValidateOptions,
  ValidationFailure,
  CompiledSchema,
  ResolvedOperation,
  RuleEvidenceStatus,
  VerificationConclusion,
  VerificationReport,
  BindingSpecInfo,
  BindingSpecVerdict,
  ProcessorScenarioFile,
  ProcessorScenario,
  ProcessorExpected,
  ProcessorAssertion,
  ProcessorDisposition,
  ProcessorPhase,
  ProcessorObservation,
  ProcessorMatch,
} from "@openbindings/core";
export {
  isTransformRef,
  resolveTransform,
  schemaObjectForm,
  validateInterface,
  parseDocument,
  validateDocument,
  formatValidationErrors,
  isOBInterface,
  compileEmbeddedSchema,
  compileExampleSchema,
  compileOperationSchema,
  OperationNotFoundError,
  ValidationError,
  MIN_SUPPORTED_VERSION,
  MAX_TESTED_VERSION,
  supportedRange,
  isSupportedVersion,
  isValidSemver,
  isHigherMajorOrPre1MinorThanMaxTested,
  isLowerThanMinSupported,
  isUnsupportedPrerelease,
  canonicalize,
  canonicalizeLocation,
  resolveRef,
  unknownFields,
  resolveOperation,
  allOperationIdentifiers,
  concludeVerification,
  isHttpUrl,
  checkBindingSpecs,
  MEDIA_TYPE,
  WELL_KNOWN_PATH,
  dereference,
  checkAssertions,
  matchProcessorObservation,
} from "@openbindings/core";

// ---------------------------------------------------------------------------
// @openbindings/invoke
// ---------------------------------------------------------------------------

export type {
  Invocation,
  BindingHandle,
  Metadata,
  ContextRequirement,
  ContextAlternative,
  ContextRequiredDetails,
  InvocationImplOptions,
  InvocationSource,
  BindingInvocationArgs,
  InvokeOptions,
  ContextStore,
  PlatformCallbacks,
  BrowserRedirectResult,
  PromptOptions,
  FileSelectOptions,
  BindingInvoker,
  TransformEvaluator,
  TransformEvaluatorWithBindings,
  BindingSelector,
  ContextResolver,
  OperationInvokerOptions,
  OperationSignature,
  OperationRequirement,
  OperationImplementation,
  OperationImplementationAssessment,
  OperationRequirementMatchOptions,
  OperationMatch,
  OperationRequirementMatches,
  OperationRequirementResolution,
  CombinedInvoker,
  FieldRouter,
  HookSlots,
  InvokeSite,
  OutputDecoder,
  RawResult,
  ResultClassifier,
  InvocationErrorCode,
} from "@openbindings/invoke";
export {
  InvocationError,
  InvocationImpl,
  single,
  contextRequiredError,
  isContextRequiredDetails,
  isPortableInvocationData,
  configValueRequirement,
  isContextRequired,
  DEFAULT_MAX_DELIVERY_UNIT_BYTES,
  resolveDeliveryUnitLimit,
  contextBearerToken,
  contextBearerTokenFor,
  contextNamedCredential,
  contextApiKey,
  contextApiKeyFor,
  contextBasicAuth,
  contextBasicAuthFor,
  contextAccessTokenFor,
  contextString,
  contextHeaders,
  contextCookies,
  contextEnvironment,
  contextConfiguration,
  contextMetadata,
  redactContext,
  normalizeContextKey,
  normalizeEndpoint,
  buildAuthHeaders,
  contextSatisfies,
  scopeContext,
  storeContextResolver,
  isTransformEvaluatorWithBindings,
  OperationInvoker,
  defaultBindingSelector,
  operationSignature,
  operationRequirement,
  matchOperationRequirement,
  resolveOperationRequirement,
  combineInvokers,
  NoInvokerError,
  BindingNotFoundError,
  BindingSelectionRequiredError,
  MissingInterfaceError,
  UnknownSourceError,
  NoTransformEvaluatorError,
  TransformRefNotFoundError,
  EmptyTransformExpressionError,
  familyName,
  isJSONContentType,
  InvokeHooks,
  USE_DEFAULT,
  assumptionWarning,
  classifyThroughHooks,
  decodeThroughHooks,
  floorStamped,
  newInvokeHooks,
  nonDiscriminatingOutput,
  siteFamilyName,
  CONTEXT_REQUIRED,
  ERR_ALREADY_CONSUMED,
  ERR_BINDING_NOT_FOUND,
  ERR_BINDING_SELECTION_REQUIRED,
  ERR_CANCELLED,
  ERR_CONNECT_FAILED,
  ERR_EVENT_LIMIT_EXCEEDED,
  ERR_EXECUTION_FAILED,
  ERR_EXPECTED_SINGLE,
  ERR_FRAME_PROTOCOL,
  ERR_INPUT_CLOSED,
  ERR_INVALID_SELECTOR,
  ERR_INVOCATION_CLOSED,
  ERR_UNSUPPORTED_FORMAT_VERSION,
  ERR_MISSING_INPUT,
  ERR_OPERATION_GRAPH_EXIT,
  ERR_OPERATION_NOT_FOUND,
  ERR_OPERATION_VALIDATION_FAILED,
  ERR_PROTOCOL,
  ERR_SELECTOR_NOT_FOUND,
  ERR_RESPONSE_ERROR,
  ERR_RUNTIME,
  ERR_REFUSED,
  ERR_SOURCE_CONFIG_ERROR,
  ERR_SOURCE_LOAD_FAILED,
  ERR_STREAM_ERROR,
  ERR_TIMEOUT,
  ERR_TOO_MANY_INPUTS,
  ERR_TRANSFORM_ERROR,
  ERR_TRANSPORT_CLOSED,
  ERR_UNKNOWN_SOURCE,
  ERR_SCHEMA_UNRESOLVED,
  ERR_TYPE_MISMATCH,
  ERR_VALIDATION_FAILED,
} from "@openbindings/invoke";

// ---------------------------------------------------------------------------
// @openbindings/synthesize
// ---------------------------------------------------------------------------

export type {
  SynthesizeSource,
  SynthesizeInput,
  SynthesizerWarning,
  SynthesisCoverageScope,
  SynthesisCoverageStatus,
  SynthesisCoverageEntry,
  SynthesisCoverage,
  SynthesisCoverageLimitation,
  SynthesizeResult,
  BindableTarget,
  SourceInspection,
  InspectionLimitation,
  InterfaceSynthesizer,
  CoverageSynthesizer,
  SourceInspector,
  CombinedSynthesizer,
  FetchInterfaceOptions,
  FetchedInterface,
  RefusedScenarioExpected,
  SynthesisSynthesizerFactory,
  SynthesisScenarioFile,
  SynthesisScenario,
  SynthesisScenarioExpected,
  SynthesizedScenarioExpected,
  NormalizedSynthesis,
  SynthesisBindingIdentity,
  NormalizedSynthesisCoverageEntry,
} from "@openbindings/synthesize";
export {
  synthesisSkeleton,
  finalizeSynthesis,
  finalizeSynthesisCoverage,
  representedCoverageEntries,
  isInterfaceSynthesizer,
  combineSynthesizers,
  combineSourceInspectors,
  NoSynthesizerError,
  SynthesisCoverageUnsupportedError,
  NoSourcesError,
  MultipleSourcesError,
  fetchInterface,
  SYNTHESIS_SCENARIO_FORMAT,
  fixedSynthesizer,
  matchSynthesisScenario,
  normalizeSynthesis,
  parseSynthesisScenarioFile,
  verifySynthesisScenario,
} from "@openbindings/synthesize";

// ---------------------------------------------------------------------------
// @openbindings/compare
// ---------------------------------------------------------------------------

export type {
  CompatibilityIssue,
  Fetcher,
  JSONValue,
  JSONObject,
  CompatResult,
} from "@openbindings/compare";
export {
  checkInterfaceCompatibility,
  checkOperationCompatibility,
  Normalizer,
  inputCompatible,
  outputCompatible,
  NotNormalizedError,
  OutsideProfileError,
  SelectorError,
  SchemaError,
} from "@openbindings/compare";
