packages:
  - packages/*
  - examples/*

overrides:
  esbuild: '>=0.28.1'
  ip-address: '>=10.1.1'
  vite: ^8.1.3

patchedDependencies:
  json-schema-library@11.6.2: patches/json-schema-library@11.6.2.patch
