// Auto-generated by ob codegen — do not edit
import {
  OperationInvoker,
  type Invocation,
  type OBInterface,
} from "@openbindings/sdk";

// --- Types ---

export interface AddItemInput {
  name: string;
  qty?: number;
}

export interface AddItemOutput {
  id: string;
}

export interface PingInput {
  message?: string;
}

export interface PingOutput {
  echoed: string;
}

// --- Per-call options ---

export interface InvokerCallOpts {
  context?: Record<string, unknown>;
  /** When set, bypass the binding selector and use this binding key directly. */
  bindingKey?: string;
  signal?: AbortSignal;
}

// --- Embedded contract ---

const INTERFACE: OBInterface = JSON.parse('{"bindings":{"addItem.rpc":{"operation":"addItem","ref":"addItem","source":"rpc"},"ping.rpc":{"operation":"ping","ref":"ping","source":"rpc"}},"name":"TestWorkersRpc","openbindings":"0.1.0","operations":{"addItem":{"description":"Add an item, returning the new item id.","input":{"properties":{"name":{"minLength":1,"type":"string"},"qty":{"default":1,"minimum":1,"type":"integer"}},"required":["name"],"type":"object"},"output":{"properties":{"id":{"type":"string"}},"required":["id"],"type":"object"}},"ping":{"description":"Health check that returns a string.","input":{"properties":{"message":{"type":"string"}},"type":"object"},"output":{"properties":{"echoed":{"type":"string"}},"required":["echoed"],"type":"object"}}},"sources":{"rpc":{"format":"workers-rpc@^1.0.0","location":"workers-rpc://test-service"}}}');

/** The OBI contract this invoker was generated against. */
export const CONTRACT: OBInterface = INTERFACE;

// --- Typed invoker ---

/**
 * Typed invoker for the "TestWorkersRpc" interface. One method per OBI
 * operation, each returning a cardinality-agnostic Invocation handle with
 * input and output types resolved from the OBI's schemas. The caller
 * decides cardinality through usage of the returned handle.
 */
export interface TestWorkersRpcInvoker {
  /** Add an item, returning the new item id. */
  addItem(opts?: InvokerCallOpts): Invocation<AddItemInput, AddItemOutput>;
  /** Health check that returns a string. */
  ping(opts?: InvokerCallOpts): Invocation<PingInput, PingOutput>;
}

export function createTestWorkersRpcInvoker(
  base: OperationInvoker,
  iface: OBInterface = INTERFACE,
): TestWorkersRpcInvoker {
  return {
    addItem: (opts) =>
      base.invoke<AddItemInput, AddItemOutput>({
        interface: iface,
        operation: "addItem",
        context: opts?.context,
        bindingKey: opts?.bindingKey,
        signal: opts?.signal,
      }),
    ping: (opts) =>
      base.invoke<PingInput, PingOutput>({
        interface: iface,
        operation: "ping",
        context: opts?.context,
        bindingKey: opts?.bindingKey,
        signal: opts?.signal,
      }),
  };
}
