// Auto-generated by ob codegen — do not edit
import {
  OperationInvoker,
  type OBInterface,
} from "@openbindings/sdk";

// --- Types ---

export interface AddItemInput {
  name: string;
  qty?: number;
}

export interface AddItemOutput {
  id: string;
}

export interface PingInput {
  message?: string;
}

export interface PingOutput {
  echoed: string;
}

// --- Invocation output ---

export interface TypedInvocationOutput<T> {
  output?: T;
  error?: { code: string; message: string; details?: unknown };
}

// --- Error ---

/**
 * Thrown by generated invoker methods when an operation fails.
 *
 * For OBI-T-08 output-validation failures the SDK yields both the
 * underlying response AND a validation error in the same event. The
 * generated method still throws (preserving the throwing-function
 * API), but attaches the response on `output` so catchers can opt
 * into using it.
 */
export class OperationError extends Error {
  readonly code: string;
  readonly details?: unknown;
  readonly output?: unknown;
  constructor(code: string, message: string, details?: unknown, output?: unknown) {
    super(message);
    this.name = 'OperationError';
    this.code = code;
    this.details = details;
    this.output = output;
  }
}

// --- Embedded contract ---

const INTERFACE: OBInterface = JSON.parse('{"bindings":{"addItem.rpc":{"operation":"addItem","ref":"addItem","source":"rpc"},"ping.rpc":{"operation":"ping","ref":"ping","source":"rpc"}},"name":"TestWorkersRpc","openbindings":"0.1.0","operations":{"addItem":{"description":"Add an item, returning the new item id.","input":{"properties":{"name":{"minLength":1,"type":"string"},"qty":{"default":1,"minimum":1,"type":"integer"}},"required":["name"],"type":"object"},"output":{"properties":{"id":{"type":"string"}},"required":["id"],"type":"object"}},"ping":{"description":"Health check that returns a string.","input":{"properties":{"message":{"type":"string"}},"type":"object"},"output":{"properties":{"echoed":{"type":"string"}},"required":["echoed"],"type":"object"}}},"sources":{"rpc":{"format":"workers-rpc@^1.0.0","location":"workers-rpc://test-service"}}}');

// --- Invoker ---

export class TestWorkersRpcInvoker {
  /** The OBI contract this invoker was generated against. Operations + schemas only; no bindings. */
  static readonly CONTRACT: OBInterface = INTERFACE;

  constructor(private readonly invoker: OperationInvoker) {}

  /**
   * Add an item, returning the new item id.
   */
  async addItem(iface: OBInterface, input: AddItemInput, context?: Record<string, unknown>): Promise<AddItemOutput> {
    for await (const event of this.invoker.invoke({
      interface: iface,
      operation: "addItem",
      input: input,
      context,
    })) {
      if (event.error) {
        throw new OperationError(event.error.code, event.error.message, event.error.details, event.output);
      }
      if (event.output !== undefined) {
        return event.output as AddItemOutput;
      }
    }
    throw new OperationError("no_data", "addItem returned no data");
  }

  /** Stream variant of addItem. */
  async *addItemStream(iface: OBInterface, input: AddItemInput, context?: Record<string, unknown>): AsyncGenerator<TypedInvocationOutput<AddItemOutput>> {
    for await (const event of this.invoker.invoke({
      interface: iface,
      operation: "addItem",
      input: input,
      context,
    })) {
      yield event as TypedInvocationOutput<AddItemOutput>;
    }
  }

  /**
   * Health check that returns a string.
   */
  async ping(iface: OBInterface, input: PingInput, context?: Record<string, unknown>): Promise<PingOutput> {
    for await (const event of this.invoker.invoke({
      interface: iface,
      operation: "ping",
      input: input,
      context,
    })) {
      if (event.error) {
        throw new OperationError(event.error.code, event.error.message, event.error.details, event.output);
      }
      if (event.output !== undefined) {
        return event.output as PingOutput;
      }
    }
    throw new OperationError("no_data", "ping returned no data");
  }

  /** Stream variant of ping. */
  async *pingStream(iface: OBInterface, input: PingInput, context?: Record<string, unknown>): AsyncGenerator<TypedInvocationOutput<PingOutput>> {
    for await (const event of this.invoker.invoke({
      interface: iface,
      operation: "ping",
      input: input,
      context,
    })) {
      yield event as TypedInvocationOutput<PingOutput>;
    }
  }

}

