// Auto-generated by ob codegen — do not edit
import {
  InterfaceClient,
  OperationInvoker,
  MemoryStore,
  normalizeContextKey,
  type BindingInvoker,
  type InterfaceClientOptions,
  type OBInterface,
  type StreamEvent,
  type ContextStore,
  type PlatformCallbacks,
  type InvocationOptions,
} from "@openbindings/sdk";

// --- Types ---

export interface AddItemInput {
  name: string;
  qty?: number;
}

export interface AddItemOutput {
  id: string;
}

export interface PingInput {
  message?: string;
}

export interface PingOutput {
  echoed: string;
}

// --- Stream event ---

export interface TypedStreamEvent<T> {
  data?: T;
  error?: { code: string; message: string; details?: unknown };
}

// --- Error ---

export class ClientOperationError extends Error {
  readonly code: string;
  readonly details?: unknown;
  constructor(code: string, message: string, details?: unknown) {
    super(message);
    this.name = 'ClientOperationError';
    this.code = code;
    this.details = details;
  }
}

// --- Options ---

export interface ConnectOptions {
  bearerToken?: string;
  contextStore?: ContextStore;
  platformCallbacks?: PlatformCallbacks;
  signal?: AbortSignal;
}

export interface ClientOptions {
  contextStore?: ContextStore;
  platformCallbacks?: PlatformCallbacks;
}

// --- Operation type map ---

type TestWorkersRpcOperations = {
  addItem: { input: AddItemInput; output: AddItemOutput; };
  ping: { input: PingInput; output: PingOutput; };
};

// --- Client ---

/** Smoke test OBI for the workers-rpc binding format. */
export class TestWorkersRpcClient {
  private invoker: OperationInvoker;
  private _client: InterfaceClient<TestWorkersRpcOperations> | null = null;
  private opts: ClientOptions;

  constructor(drivers: BindingInvoker[], opts?: ClientOptions) {
    this.invoker = new OperationInvoker(drivers);
    this.opts = opts ?? {};
  }

  /**
   * Connect to a service. Resolves the OBI, sets up auth context,
   * and prepares the client for operation calls.
   */
  async connect(url: string, opts?: ConnectOptions): Promise<void> {
    const store = opts?.contextStore ?? this.opts.contextStore ?? new MemoryStore();
    const callbacks = opts?.platformCallbacks ?? this.opts.platformCallbacks;
    if (opts?.bearerToken) {
      const key = normalizeContextKey(url);
      await store.set(key, { bearerToken: opts.bearerToken });
    }
    const runtimeInvoker = this.invoker.withRuntime(store, callbacks);
    const client = new InterfaceClient<TestWorkersRpcOperations>(INTERFACE, runtimeInvoker, {
      contextStore: store,
      platformCallbacks: callbacks,
    });
    await client.resolve(url, { signal: opts?.signal });
    if (client.state.kind === 'error') {
      throw new Error(client.state.message);
    }
    this._client = client;
  }

  private get client(): InterfaceClient<TestWorkersRpcOperations> {
    if (!this._client) throw new Error('Not connected. Call connect() first.');
    return this._client;
  }

  /**
   * Add an item, returning the new item id.
   */
  async addItem(input: AddItemInput, options?: InvocationOptions): Promise<AddItemOutput> {
    for await (const event of this.client.invoke("addItem", input, options)) {
      if (event.error) {
        throw new ClientOperationError(event.error.code, event.error.message, event.error.details);
      }
      if (event.data !== undefined) {
        return event.data as AddItemOutput;
      }
    }
    throw new ClientOperationError("no_data", "addItem returned no data");
  }

  /** Stream variant of addItem. */
  async *addItemStream(input: AddItemInput, options?: InvocationOptions): AsyncGenerator<TypedStreamEvent<AddItemOutput>> {
    for await (const event of this.client.invoke("addItem", input, options)) {
      yield event as TypedStreamEvent<AddItemOutput>;
    }
  }

  /**
   * Health check that returns a string.
   */
  async ping(input: PingInput, options?: InvocationOptions): Promise<PingOutput> {
    for await (const event of this.client.invoke("ping", input, options)) {
      if (event.error) {
        throw new ClientOperationError(event.error.code, event.error.message, event.error.details);
      }
      if (event.data !== undefined) {
        return event.data as PingOutput;
      }
    }
    throw new ClientOperationError("no_data", "ping returned no data");
  }

  /** Stream variant of ping. */
  async *pingStream(input: PingInput, options?: InvocationOptions): AsyncGenerator<TypedStreamEvent<PingOutput>> {
    for await (const event of this.client.invoke("ping", input, options)) {
      yield event as TypedStreamEvent<PingOutput>;
    }
  }

}

// --- Embedded interface ---

const INTERFACE: OBInterface = JSON.parse('{"bindings":{"addItem.rpc":{"operation":"addItem","ref":"addItem","source":"rpc"},"ping.rpc":{"operation":"ping","ref":"ping","source":"rpc"}},"name":"TestWorkersRpc","openbindings":"0.1.0","operations":{"addItem":{"description":"Add an item, returning the new item id.","input":{"properties":{"name":{"minLength":1,"type":"string"},"qty":{"default":1,"minimum":1,"type":"integer"}},"required":["name"],"type":"object"},"output":{"properties":{"id":{"type":"string"}},"required":["id"],"type":"object"}},"ping":{"description":"Health check that returns a string.","input":{"properties":{"message":{"type":"string"}},"type":"object"},"output":{"properties":{"echoed":{"type":"string"}},"required":["echoed"],"type":"object"}}},"sources":{"rpc":{"format":"workers-rpc@^1.0.0","location":"workers-rpc://test-service"}}}');
